FROM maven:3.9.16-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn dependency:resolve
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=builder ./app/target/*.jar ./application.jar
EXPOSE 8080

ENV POSTGRES_HOST=localhost
RUN echo "the env var POSTGRES_HOST IS $POSTGRES_HOST"

ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=production", "application.jar"]

